[tool.poetry]
name = "kafkoroutine"
version = "0.1.0"
description = "Asynchronous wrappers for kafka-python, integrating Kafka with Python's asyncio."
authors = ["Michal Polit <mpolit@protonmail.com>"]
readme = "README.md"
homepage = "https://github.com/mpol1t/kafkoroutine"
repository = "https://github.com/mpol1t/kafkoroutine"
license = "MIT"
packages = [{include = "kafkoroutine"}]

[tool.poetry.dependencies]
python = "^3.11"
kafka-python = "^2.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"
mock = "^5.1.0"
coverage = "^7.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"